### ISSUE TITLE
Problems with two consecutive SMA instructions.

### ISSUE THREAD

**Issue by hneemann** [DoctorWkt/CSCv2#1]
I like your processor design and I'm trying to run the processor in my simulator using DIL chips.
I observed that some programs work and others don't. While digging down I found the following problem: 
If two SMA instructions follow directly on each other, the writeRAM signal does not 
go high between the write cycles. This means the data and the address of the RAM does change while \WE and \CE both are low.
Are you sure the RAM chip is able to deal with this in a defined way?

**Comment by hneemann** [comment]
After looking at some datasheets, I think it's okay to do it this way. 
I reworked my SRAM implementation and now your CPU is running nicely.
Do you agree if I add your CPU to my simulator as a more complex example of a 74xx circuit?

![CrazySmallCPU](https://user-images.githubusercontent.com/7190563/59221445-95d49300-8bc7-11e9-8c85-88b7b44c26b4.png)

**Comment by DoctorWkt** [comment]
Helmut, yes certainly you can use my CPU as an example. Can you leave a link to your simulator here? Thanks, Warren

**Comment by hneemann** [comment]
Hi Warren, 
you can find the simulator [here](https://github.com/hneemann/Digital). The latest pre release - which is necessary because of the SRAM timing issue i mentioned above - is available [here](https://infdigital.dhbw-mosbach.de/). 
After unziping you can find your CPU in the folder "examples/74xx".
