### ISSUE TITLE
Clock sync and control signals

### ISSUE THREAD

**Issue by Johnlon** [DoctorWkt/CSCv2#2]
Hi enjoying the vids.

Could you please put something together specifically addressing the question of synchronising changes to the control lines with the clocking of the sequential components.

Basically the same point Ben Eater makes here : https://www.youtube.com/watch?v=X7rCxs1ppyY&t=4m29s

In the manual testing one manually sets up the ctrl lines and only then does one trigger the clock.
So the control line setup must happen reliably before the clock. 
I am assuming that some aspect of the crazy small computer ensures this timing but I wasn't able to find it in the videos.

Can you clarify how (or whether) this same concern applies to the CSC arch?

Thanks again

**Comment by DoctorWkt** [comment]
John, thanks for the suggestion. I've actually been spending more time working on the big brother to the CSCv2, my [8-bit CSCvon8 CPU](https://github.com/DoctorWkt/CSCvon8). If you don't mind, I've written a [blog entry](https://minnie.tuhs.org/Blog/2019_07_17_CSCon8_timing_notes.html) about the CSCvon8 to answer your question. Right now it's probably a draft as I want to add some more links, but it should do as a good exposition on clock timing for you. Let me know if anything is not clear. Cheers, Warren

**Comment by Johnlon** [comment]
Wow warren thanks for the reply - sorry only just seen the reply.

Really appreciate the content !

I hope you don't mind as I've referenced it in [my GitHub README] (https://github.com/portingle/spam-1)

--

I'm still in the planning stage myself. Something I will build with my son.

I'm simulating everything first and reading as much as possible which is how I came to your content which is much appreciated and has inspired me greatly.

I'm concentrating on working out the tool chain primarily and wanted an assembler and hopefully come kind of higher level language (C derivative). 

I've finished an assembler - written using Google Sheets (which I think is pretty novel) but am still researching how one might adapt some existing higher level compiler to an arbitrary CPU.

If you are interested then ...   https://github.com/portingle/spam-1
and also you can see the assembler here ... https://www.youtube.com/playlist?list=PLdLE_IdL0sqyAxmmHNbp0Q6dVWFVW8zQQ

Any advice on getting to a working compiler would be appreciated !!


It occurs to me that a useful resource would be a curated collection of software that could be adapted by hobbyists. Eg what a Fib algorithm looks like - since that's apparently the "hello world" of home brew CPUs.

But also more complex things like advice and examples of how to adapt a compilers (eg like TTLCpu https://github.com/szoftveres/ttlcpu/blob/master/example.c) or the compiler for gigatron.
What's definitely missing is "how?".

I wonder if it's possible to build a template compiler with a set of hooks where one fills in one's mapping to ones own assembler??

Hmm?

Anyway thanks for any advice.
